### ISSUE TITLE
Partnership proposition

### ISSUE THREAD

**Issue by AdaptCharm** [circa94/JSlither#14]
@circa94 Please tell me your email address. I have a good partnership proposition for you.

If you don't want to make it public, you can email me at jamie@jamie.no.

**Comment by Kogs** [comment]
@TheGoldenXY  see http://www.thehardcoders.de/#/contact

**Comment by khoinguyen23041996** [comment]
@Kogs Please check message in gmail of you . I have sent a project to your inbox
