### ISSUE TITLE
packets same on public server(s) ?

### ISSUE THREAD

**Issue by agarioBotDev** [circa94/JSlither#3]
hello,

are the packets for the public servers the same ? 

greats,
david

**Comment by Kogs** [comment]
@agarioBotDev they should be the same.

**Comment by agarioBotDev** [comment]
@Kogs @circa94 so how do i get snakeID for newSnakePacket ?

**Comment by nightwolf93** [comment]
@agarioBotDev You generate a random ID on your server

**Comment by agarioBotDev** [comment]
@nightwolf93 i mean the spawn packet sended from the client, where can i find it ? I thought it is newSnakePacket lol

**Comment by nightwolf93** [comment]
There is no spawn packet sended by the client. The server is the only who have this possibilities.

**Comment by agarioBotDev** [comment]
@nightwolf93 but if you press the "Play" button somehow the slitherio server have to notice that and create anew snake ?? or am i wrong

**Comment by nightwolf93** [comment]
Yeah this is the SetUsernamePacket, after that the server send the InitialPacket and after your snake ;)

**Comment by agarioBotDev** [comment]
@nightwolf93 

``` javascript
var exports = module.exports = {};

function SetUsernamePacket(u1, u2, username) {
  this.unknown1 = u1;
  this.unknown2 = u2;
  this.packetType = 97;
  this.username = username;
}

exports.SetUsernamePacket = function() {
    return new SetUsernamePacket();
}
```

so this packet is not finished ? ;)

**Comment by nightwolf93** [comment]
This packet is done, look at where the id is generated. JSlither is a server, not a client

**Comment by Kogs** [comment]
The Flow is 
Client sends to Server username 
Clients gets from Server where its Snake should spawn

**Comment by circa94** [comment]
We are currenty not using this packege. Look at Server.js line 95 how we handle it

**Comment by agarioBotDev** [comment]
@circa94 @Kogs @nightwolf93 on real server, how does the username packet look like ? :)

**Comment by circa94** [comment]
like in this repo :)

**Comment by agarioBotDev** [comment]
@circa94 so like:

``` javascript
[ u1,u2, 97, usename.toBytes() ]
```

**Comment by circa94** [comment]
@agarioBotDev yes
