### ISSUE TITLE
Impossible move the snake

### ISSUE THREAD

**Issue by ritney78** [circa94/JSlither#4]
My snake is stuck at launch, how correct her? thank you

**Comment by nightwolf93** [comment]
It's not actually done.

**Comment by circa94** [comment]
This is okay so. The movement is currently under development.

**Comment by ritney78** [comment]
Oh, okay thanks for your response

**Comment by circa94** [comment]
@ritney78 i made a new check in. this is my latest work on the movement but still not finished. maybe you and others can help to make it work

**Comment by ritney78** [comment]
ty, i'm trying it now

**Comment by ritney78** [comment]
what is this error?
https://gyazo.com/2bbd4a6163ee5f8fe9fa3db2ecb0c491
thanks
