### ISSUE TITLE
async file not found?

### ISSUE THREAD

**Issue by ritney78** [circa94/JSlither#5]
https://gyazo.com/2bbd4a6163ee5f8fe9fa3db2ecb0c491
I have a problem when I try to connect how to fix it?
thanks

**Comment by Kogs** [comment]
try `npm install async`

**Comment by circa94** [comment]
@ritney78 oh sorry, i have to update the readme.
pease run: `npm install async`

we will use this later maybe for async operations

**Comment by ritney78** [comment]
thank's, it's work just impossible move i'm teleported/freeze/invisible snake

https://gyazo.com/6a3995b0645f8669f63c52e92a80922c

**Comment by Kogs** [comment]
@ritney78 the project is still in development. We know that the movement is not working
