### ISSUE TITLE
Combining projects

### ISSUE THREAD

**Issue by mZer0ne** [circa94/JSlither#7]
Hi, I realized that one project is not a one off! Let us unite efforts?
https://GitHub.com/PlitherProject

**Comment by circa94** [comment]
I know this project, i also updated there the protocol. But they will make a Java server and i will create with the community a node server.

**Comment by mZer0ne** [comment]
my project is also based off node js

**Comment by circa94** [comment]
Aaahh okay. Good. You have anything already done?

**Comment by mZer0ne** [comment]
fully implemented client platform, I am now copied your branch will start modifying it

**Comment by circa94** [comment]
Cool! I will have a look on it. Sure we may can combine our projects

**Comment by mZer0ne** [comment]
Now while I do the upgrade at their fold and you'll see later how to get it, I do not mind if I start adoptatsiyu your server platform for the client?

**Comment by mZer0ne** [comment]
Then I'll disconnect the client from the server structure of their developments, and will be adapted to you

**Comment by mZer0ne** [comment]
Skype: https://join.skype.com/o753J0fGY2z2
