### ISSUE TITLE
getting, port or server must be provided error.

### ISSUE THREAD

**Issue by cmdstack** [circa94/JSlither#8]
i ran:

npm install
npm start
--Got error: port or server must be provided
tried:
npm start 127.0.0.1
npm start port 8080
npm start server 127.0.0.1

**Comment by circa94** [comment]
you only have to run: `npm install` and then `npm start`

make sure, port 8080 ist not used by an other application

**Comment by cmdstack** [comment]
That's what I tried originally.

http://s23.postimg.org/4lm02qvez/Untitled.png

**Comment by circa94** [comment]
Maybe fetch the newest version an try again. Otherwhise insert a port number in the serverjs where the error is

**Comment by ezamelczyk** [comment]
I had the same problem. Replacing process.env.PORT in WebSocket initialisation with 8080 fixed it.

**Comment by cmdstack** [comment]
already did that

process.env.PORT || 8080

**Comment by circa94** [comment]
when so many guys have this problem, i will set port 8080 hardcoded in the next version instead of process.env.PORT

**Comment by Kogs** [comment]
With the new version the port is provided over the config.json. So you dont have the problem with process.env.PORT and its easy to change.
